name: Generate Snake

on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual runs
  push: # Run when you push to main
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Hs30   # <-- your GitHub username
          outputs: dist/snake.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
