name: Generate Snake

on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual runs
  push: # Also run when you push to main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Hs30   # <-- your username
          outputs: dist/snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
